server:
  port: 8088
spring:
  application:
    name: boot-admin
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
    platform:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  messages:
    basename: i18n/messages
  redis:
    host:
    password:
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
      #更新 插入 查询策略
      update-strategy: ignored
      insert-strategy: ignored
      select-strategy: ignored

management:
  endpoints:
    web:
      exposure:
        include: '*'
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

boot:
  admin:
    name: boot-admin
    version: 1.0.0
    copyrightYear: 2020
    demoEnabled: false
    attachmentType: 1
    tokenType: 1
    oss:
      local:
        # 注意 填写当前路径 如果使用docker请创建当前填写路径
        profile: /root/log
      aliyun:
        endPoint:
        accessKey:
        accessSecret:
        bucketName:
# alibaba jetcache wiki https://github.com/alibaba/jetcache/wiki/Config_CN
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hiddenPackages: com.hb0730.boot.admin
  local:
    boot-admin:
      type: caffeine
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      limit: 100
  remote:
    boot-admin:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      uri: redis://${spring.redis.password}@${spring.redis.host}:${spring.redis.port}
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
